# Railway Deployment
# This file configures Railway deployment

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "3000"
